[package]
name = "algebraic_surfaces"
version = "0.1.0"
authors = ["asd"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra = "*"
kiss3d = "*"